### Imports

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [19]:
df = pd.read_csv("Datasets/KenPom Barttorvik.csv")
df

,YEAR,CONF,CONF ID,QUAD NO,QUAD ID,TEAM NO,TEAM ID,TEAM,SEED,ROUND,...,BADJT RANK,AVG HGT RANK,EFF HGT RANK,EXP RANK,TALENT RANK,FT% RANK,OP FT% RANK,PPPO RANK,PPPD RANK,ELITE SOS RANK
0,2024,MAC,17,61,1,1079,2,Akron,14,0,...,276,238,199,19,176,164,47,122,51,249
1,2024,SEC,28,63,3,1078,3,Alabama,4,0,...,13,33,8,156,106,10,314,2,263,7
2,2024,P12,24,63,3,1077,8,Arizona,2,0,...,16,50,37,196,7,195,134,8,14,47
3,2024,SEC,28,64,4,1076,12,Auburn,4,0,...,58,86,76,127,69,59,284,12,8,69
4,2024,B12,7,63,3,1075,14,Baylor,3,0,...,274,31,22,304,34,97,254,15,155,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1074,2008,BE,8,1,1,5,235,West Virginia,7,16,...,225,18,115,181,61,209,16,22,32,49
1075,2008,SB,26,1,1,4,236,Western Kentucky,12,16,...,111,160,179,55,131,127,214,27,28,203
1076,2008,BSth,10,4,4,3,239,Winthrop,13,64,...,301,231,206,89,236,339,190,170,12,179
1077,2008,B10,6,3,3,2,240,Wisconsin,3,16,...,301,51,35,98,12,118,117,60,2,57
1078,2008,A10,1,1,1,1,244,Xavier,3,8,...,225,149,92,63,147,20,86,4,44,85

In [22]:
X = df.drop(['TEAM', 'WIN%'], axis=1)  
y = df['WIN%']
X.head()

,YEAR,CONF,CONF ID,QUAD NO,QUAD ID,TEAM NO,TEAM ID,SEED,ROUND,K TEMPO,...,BADJT RANK,AVG HGT RANK,EFF HGT RANK,EXP RANK,TALENT RANK,FT% RANK,OP FT% RANK,PPPO RANK,PPPD RANK,ELITE SOS RANK
0,2024,MAC,17,61,1,1079,2,14,0,66.7747,...,276,238,199,19,176,164,47,122,51,249
1,2024,SEC,28,63,3,1078,3,4,0,74.1625,...,13,33,8,156,106,10,314,2,263,7
2,2024,P12,24,63,3,1077,8,2,0,73.3760,...,16,50,37,196,7,195,134,8,14,47
3,2024,SEC,28,64,4,1076,12,4,0,70.9629,...,58,86,76,127,69,59,284,12,8,69
4,2024,B12,7,63,3,1075,14,3,0,66.8428,...,274,31,22,304,34,97,254,15,155,1

In [21]:
label_encoder = LabelEncoder()
X['Team_encoded'] = label_encoder.fit_transform(df['TEAM'])

# split into into training and testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, random_state=0)

# Fit 
model = LinearRegression()
model.fit(X_train, y_train)

# Score
R2 = model.score(X_test, y_test)
print("R^2 score:", R2)

AttributeError: module 'numpy' has no attribute 'matrix'

In [18]:
coefficients = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_
})
print(coefficients)

ValueError: All arrays must be of the same length