In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, cross_validate
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
df = pd.read_csv("ShootingSplits_HeatCheckTourwTrap.csv")
df.head(3)

,Unnamed: 0,YEAR,TEAM NO,TEAM ID,TEAM,CONF,DUNKS FG%,DUNKS SHARE,DUNKS FG%D,DUNKS D SHARE,...,POWER,PATH,DRAW,WINS,POOL VALUE,POOL S-RANK,NCAA S-RANK,VAL Z-SCORE,POWER-PATH,Within Trapezoid of Excellence
0,0,2024,1079,2,Akron,MAC,97.2,6.8,90.6,5.6,...,54.3,79.8,NaN,0,2.0,54,54,NaN,-25.5,0
1,1,2024,1078,3,Alabama,SEC,81.9,9.5,89.2,7.3,...,77.3,66.4,NaN,4,39.0,13,16,NaN,10.9,0
2,2,2024,1077,8,Arizona,P12,91.2,11.9,89.3,5.9,...,86.2,64.6,NaN,2,91.8,2,6,NaN,21.6,0